import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/**
 * Flat config for the ESLint CLI. `next lint` is deprecated and removed in
 * Next 16, so `pnpm lint` runs `eslint` directly against this file.
 */
const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      ".venv/**",
      // Generated data + the re-embedded standalone page (see refresh.sh).
      "data.json",
      "public/data.json",
      "public/divisions/**",
      "public/index.html",
      // Generated by Next on every build.
      "next-env.d.ts",
      // Legacy modular11 helper: a fragment pasted into the browser console.
      ".playwright-scrape-matches.js",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
